version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP Server
    restart: unless-stopped
